"""Added Test3 table with extra column

Revision ID: aeedebcd6b11
Revises: 43c343f319e9
Create Date: 2017-03-19 11:59:57.584387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeedebcd6b11'
down_revision = '43c343f319e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('erased', sa.Boolean(), nullable=False),
    sa.Column('another_column', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests3_description'), 'tests3', ['description'], unique=False)
    op.create_index(op.f('ix_tests3_id'), 'tests3', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests3_id'), table_name='tests3')
    op.drop_index(op.f('ix_tests3_description'), table_name='tests3')
    op.drop_table('tests3')
    # ### end Alembic commands ###
